using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.Odbc;

namespace ADBM.api.Models
{
    public class CustomerDBHandler
    {

        private OdbcConnection con;
        private void connection()
        {
            string constring = ConfigurationManager.ConnectionStrings["csADBMSamp"].ToString();
            con = new OdbcConnection(constring);
        }

        // 1. ********** Insert Item **********
        // Warning!  adbmsamp database uses a string id for Customer.  It is not autogenerated.  This code will not work if you try to insert a customer that conflicts with another customer "number".
        public bool InsertItem(CustomerModel cList)
        {
            connection();
            int i = 0;
            using (con)
            {
                string query = "INSERT INTO \"CA Customers\" (Customer, FirmName, LastName, FirstName, City, State, BusinessPh) VALUES('" + cList.Customer + "','" + cList.FirmName + "','" + cList.LastName + "','" + cList.FirstName + "','" + cList.City + "','" + cList.State + "','" + cList.BusinessPhone + "')";
                OdbcCommand cmd = new OdbcCommand(query, con);
                try
                {
                    con.Open();
                    i = cmd.ExecuteNonQuery();
                }
                catch (Exception exception) { string ex = exception.Message.ToString(); }
                finally
                {
                    con.Close();  //when "using" you probably don't need this
                }
            }
            if (i >= 1)
                return true;
            else
                return false;
        }

        // 2. ********** Get All Item List **********
        public List<CustomerModel> GetCustomerList()
        {
            List<CustomerModel> cList = new List<CustomerModel>();
            DataTable dt = new DataTable();
            connection();
            using (con)
            {
                string query = "SELECT * FROM \"CA Customers\"";
                OdbcCommand cmd = new OdbcCommand(query, con);
                OdbcDataAdapter adapter = new OdbcDataAdapter(cmd);
                try
                {
                    con.Open();
                    adapter.Fill(dt);
                }
                catch (Exception exception) { string ex = exception.Message.ToString(); }
                finally
                {
                    con.Close();
                }
            }
            foreach (DataRow dr in dt.Rows)
            {
                cList.Add(new CustomerModel
                {
                    Customer = Convert.ToString(dr["Customer"]),
                    FirmName = Convert.ToString(dr["FirmName"]),
                    LastName = Convert.ToString(dr["LastName"]),
                    FirstName = Convert.ToString(dr["FirstName"]),
                    City = Convert.ToString(dr["City"]),
                    State = Convert.ToString(dr["State"]),
                    BusinessPhone = Convert.ToString(dr["BusinessPh"])
                });
            }
            return cList;
        }

        // 3. ********** Update Item Details **********
        public bool UpdateCustomer(CustomerModel cList)
        {
            connection();
            int i = 0;
            using (con)
            {
                string query = "UPDATE \"CA Customers\" SET FirmName = '" + cList.FirmName + "', LastName = '" + cList.LastName + "', FirstName = '" + cList.FirstName + "', City = '" + cList.City + "', State = '" + cList.State + "', BusinessPh = '" + cList.BusinessPhone + "' WHERE Customer = '" + cList.Customer + "'";
                OdbcCommand cmd = new OdbcCommand(query, con);
                con.Open();
                try
                {
                    i = cmd.ExecuteNonQuery();
                }
                catch (Exception exception)
                { string ex = exception.Message.ToString(); }
                finally
                {
                    con.Close();
                }
            }
            if (i >= 1)
                return true;
            else
                return false;
        }

        // 4. ********** Delete Item **********
        public bool DeleteCustomer(string id)
        {
            connection();
            int i = 0;
            using (con)
            {
                string query = "DELETE FROM \"CA Customers\" WHERE Customer = '" + id.ToString() + "'";
                OdbcCommand cmd = new OdbcCommand(query, con);
                con.Open();
                try
                {
                    i = cmd.ExecuteNonQuery();
                }
                catch (Exception exception) { string ex = exception.Message.ToString(); }
                finally
                {
                    con.Close();
                }
            }
            if (i >= 1)
                return true;
            else
                return false;
        }

    }
}